# Generated by Django 6.0.3 on 2026-03-06 21:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('industry_planner', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('start_job', 'start_job')], db_index=True, max_length=30)),
                ('status', models.CharField(choices=[('ready', 'ready'), ('assigned', 'assigned'), ('temp_done', 'temp_done'), ('verified', 'verified'), ('failed', 'failed'), ('cancelled', 'cancelled')], db_index=True, default='ready', max_length=30)),
                ('locked_until', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('attempt', models.IntegerField(default=0)),
                ('priority_score', models.IntegerField(db_index=True, default=0)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.IntegerField(default=1)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_work_items', to=settings.AUTH_USER_MODEL)),
                ('plan_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_items', to='industry_planner.planjob')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_items', to='industry_planner.project')),
            ],
        ),
        migrations.CreateModel(
            name='WorkEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(db_index=True, max_length=50)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_events', to=settings.AUTH_USER_MODEL)),
                ('work_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='workforce.workitem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='workitem',
            index=models.Index(fields=['status', 'priority_score', 'created_at'], name='workforce_w_status_745728_idx'),
        ),
        migrations.AddIndex(
            model_name='workitem',
            index=models.Index(fields=['assigned_to', 'status'], name='workforce_w_assigne_290d42_idx'),
        ),
    ]
