# Generated by Django 6.0.3 on 2026-03-06 21:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('assets', 'assets'), ('jobs', 'jobs'), ('wallet_journal', 'wallet_journal'), ('wallet_transactions', 'wallet_transactions')], db_index=True, max_length=40)),
                ('corporation_id', models.BigIntegerField(db_index=True)),
                ('wallet_division', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('started', 'started'), ('ok', 'ok'), ('failed', 'failed')], db_index=True, max_length=20)),
                ('rows_written', models.IntegerField(default=0)),
                ('error_text', models.TextField(blank=True, default='')),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CorpJobSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_id', models.BigIntegerField(db_index=True)),
                ('activity_id', models.IntegerField(db_index=True)),
                ('blueprint_id', models.BigIntegerField(blank=True, null=True)),
                ('blueprint_type_id', models.BigIntegerField(db_index=True)),
                ('product_type_id', models.BigIntegerField(db_index=True)),
                ('runs', models.IntegerField(default=0)),
                ('status', models.CharField(blank=True, default='', max_length=30)),
                ('installer_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('output_location_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('sync_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='corp_sync.syncrun')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'output_location_id'], name='corp_sync_c_status_0cbbf7_idx'), models.Index(fields=['installer_id', 'activity_id'], name='corp_sync_c_install_895ae4_idx')],
            },
        ),
        migrations.CreateModel(
            name='CorpAssetSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_id', models.BigIntegerField(db_index=True)),
                ('type_id', models.BigIntegerField(db_index=True)),
                ('location_id', models.BigIntegerField(db_index=True)),
                ('location_type', models.CharField(blank=True, default='', max_length=100)),
                ('location_flag', models.CharField(blank=True, default='', max_length=100)),
                ('quantity', models.BigIntegerField(default=0)),
                ('is_singleton', models.BooleanField(default=False)),
                ('is_blueprint_copy', models.BooleanField(default=False)),
                ('sync_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='corp_sync.syncrun')),
            ],
            options={
                'indexes': [models.Index(fields=['location_id', 'location_flag'], name='corp_sync_c_locatio_e926e1_idx'), models.Index(fields=['type_id', 'location_id'], name='corp_sync_c_type_id_b6302b_idx')],
            },
        ),
    ]
