# Generated by Django 6.0.3 on 2026-03-06 22:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corp_sync', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletJournalSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry_id', models.BigIntegerField(db_index=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('context_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('context_id_type', models.CharField(blank=True, default='', max_length=100)),
                ('entry_date', models.DateTimeField(db_index=True)),
                ('description', models.TextField(blank=True, default='')),
                ('first_party_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('reason', models.TextField(blank=True, default='')),
                ('ref_type', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('second_party_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('tax', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('tax_receiver_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('sync_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wallet_journal_entries', to='corp_sync.syncrun')),
            ],
            options={
                'indexes': [models.Index(fields=['ref_type', 'entry_date'], name='corp_sync_w_ref_typ_60d757_idx'), models.Index(fields=['context_id', 'context_id_type'], name='corp_sync_w_context_e9de06_idx')],
            },
        ),
        migrations.CreateModel(
            name='WalletTransactionSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_id', models.BigIntegerField(db_index=True)),
                ('client_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('transaction_date', models.DateTimeField(db_index=True)),
                ('is_buy', models.BooleanField(db_index=True, default=False)),
                ('journal_ref_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('location_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('quantity', models.BigIntegerField(default=0)),
                ('type_id', models.BigIntegerField(db_index=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('sync_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wallet_transactions', to='corp_sync.syncrun')),
            ],
            options={
                'indexes': [models.Index(fields=['type_id', 'transaction_date'], name='corp_sync_w_type_id_d62b41_idx'), models.Index(fields=['is_buy', 'transaction_date'], name='corp_sync_w_is_buy_df0085_idx')],
            },
        ),
    ]
