# Generated by Django 6.0.3 on 2026-03-06 21:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EsiToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purpose', models.CharField(choices=[('full', 'full'), ('sales', 'sales'), ('corp', 'corp')], db_index=True, max_length=20)),
                ('refresh_token_enc', models.TextField()),
                ('access_token', models.TextField(blank=True, default='')),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('scopes', models.TextField(blank=True, default='')),
                ('last_refresh_error', models.TextField(blank=True, default='')),
                ('owner_character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='accounts.character')),
            ],
            options={
                'ordering': ['purpose', 'owner_character_id'],
            },
        ),
    ]
