# Generated by Django 6.0.3 on 2026-03-06 21:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity_id', models.IntegerField(db_index=True)),
                ('blueprint_type_id', models.BigIntegerField(db_index=True)),
                ('product_type_id', models.BigIntegerField(db_index=True)),
                ('runs', models.IntegerField(default=0)),
                ('expected_duration_s', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=0)),
                ('probability', models.FloatField(blank=True, null=True)),
                ('is_advanced', models.BooleanField(default=False)),
                ('params_hash', models.CharField(db_index=True, max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('priority', models.IntegerField(db_index=True, default=3)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('active', 'active'), ('paused', 'paused'), ('done', 'done'), ('archived', 'archived')], db_index=True, default='draft', max_length=20)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PlanMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material_type_id', models.BigIntegerField(db_index=True)),
                ('quantity_total', models.BigIntegerField(default=0)),
                ('activity_id', models.IntegerField(blank=True, null=True)),
                ('level', models.IntegerField(default=0)),
                ('is_input', models.BooleanField(default=True)),
                ('is_intermediate', models.BooleanField(default=False)),
                ('plan_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='industry_planner.planjob')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_materials', to='industry_planner.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='planjob',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_jobs', to='industry_planner.project'),
        ),
        migrations.CreateModel(
            name='ProjectTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type_id', models.BigIntegerField(db_index=True)),
                ('quantity', models.BigIntegerField(default=0)),
                ('is_final_output', models.BooleanField(default=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='industry_planner.project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
